

device:
  model: 49PUS640112

# all of this needs checking for this TV

actions:
  skip_ad:
    - keypress: KEYCODE_ENTER
  switch_off:
    - keypress: KEYCODE_POWER
  youtube_search:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: YOUTUBE_PKG
      activity: YOUTUBE_ACT
    - wait: 5
    - keypress: KEYCODE_MEDIA_STOP
    - wait: 5
    - keypress: KEYCODE_SEARCH
    - wait: 1
    - keypress: KEYCODE_BACK
    - wait: 1
    - keypress: KEYCODE_MOVE_END
    - wait: 1
    - delete: 50
    - text: <query>
    - keypress: KEYCODE_ENTER
  netflix_search:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: NETFLIX_PKG
      activity: NETFLIX_ACT
    - wait: 20
    - keypress: KEYCODE_SEARCH
    - wait: 5
    - keypress: KEYCODE_MOVE_END
    - wait: 1
    - delete: 50
    - text: <query>
  amazon_search:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: AMAZON_PKG
      activity: AMAZON_ACT
    - wait: 10
    - keypress: KEYCODE_DPAD_LEFT
    - wait: 1
    - keypress: KEYCODE_ENTER
    - wait: 5
    - text: <query>
    - wait: 5
    - keypress: KEYCODE_DPAD_UP
  volume_up:
    - keypress: KEYCODE_VOLUME_UP
  volume_down:
    - keypress: KEYCODE_VOLUME_DOWN
  volume_set:
    - keypress: KEYCODE_VOLUME_UP
  type:
    - text: <query>

programmes:
  peppa pig:
    - keypress: KEYCODE_HOME
    - wait: 5
    - raw: shell am start -c android.intent.category.LEANBACK_LAUNCHER -a android.intent.action.VIEW -d https://www.netflix.com/watch/80025494 -f 0x10808000 -e source 30 com.netflix.ninja/.MainActivity
    - wait: 10
    - keypress: KEYCODE_ENTER
  # peppa pig:
  #   - app: NETFLIX_PKG
  #     activity: NETFLIX_ACT
  #   - wait: 20
  #   - keypress: KEYCODE_SEARCH
  #   - wait: 5
  #   - keypress: KEYCODE_MOVE_END
  #   - wait: 1
  #   - delete: 50
  #   - text: peppa pig
  #   - wait: 5
  #   - keypress_multiple: KEYCODE_DPAD_RIGHT
  #     times: 6
  #   - keypress: KEYCODE_ENTER
  paw patrol:
    - keypress: KEYCODE_HOME
    - wait: 5
    - raw: shell am start -c android.intent.category.LEANBACK_LAUNCHER -a android.intent.action.VIEW -d https://www.netflix.com/watch/80026226 -f 0x10808000 -e source 30 com.netflix.ninja/.MainActivity
    - wait: 10
    - keypress: KEYCODE_ENTER
  diggers for kids:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: YOUTUBE_PKG
      activity: YOUTUBE_ACT
    - wait: 5
    - keypress: KEYCODE_MEDIA_STOP
    - wait: 5
    - keypress: KEYCODE_SEARCH
    - wait: 2
    - keypress: KEYCODE_BACK
    - wait: 2
    - keypress: KEYCODE_MOVE_END
    - wait: 1
    - delete: 50
    - text: diggers for kids
    - keypress: KEYCODE_ENTER
    - keypress_multiple: KEYCODE_DPAD_DOWN
      times: 6
    - keypress_rand: KEYCODE_DPAD_RIGHT
      min_times: 0
      max_times: 30
    - keypress: KEYCODE_ENTER
  nursery rhymes:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: YOUTUBE_PKG
      activity: YOUTUBE_ACT
    - wait: 5
    - keypress: KEYCODE_MEDIA_STOP
    - wait: 5
    - keypress: KEYCODE_SEARCH
    - wait: 2
    - keypress: KEYCODE_BACK
    - wait: 2
    - keypress: KEYCODE_MOVE_END
    - wait: 1
    - delete: 50
    - text: lbb junior
    - keypress: KEYCODE_ENTER
    - keypress_multiple: KEYCODE_DPAD_DOWN
      times: 6
    - keypress_rand: KEYCODE_DPAD_RIGHT
      min_times: 10
      max_times: 30
    - keypress: KEYCODE_ENTER
  geckos garage:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: YOUTUBE_PKG
      activity: YOUTUBE_ACT
    - wait: 5
    - keypress: KEYCODE_MEDIA_STOP
    - wait: 5
    - keypress: KEYCODE_SEARCH
    - wait: 2
    - keypress: KEYCODE_BACK
    - wait: 2
    - keypress: KEYCODE_MOVE_END
    - wait: 1
    - delete: 50
    - text: geckos garage
    - keypress: KEYCODE_ENTER
    - keypress_multiple: KEYCODE_DPAD_DOWN
      times: 6
    - keypress_rand: KEYCODE_DPAD_RIGHT
      min_times: 10
      max_times: 30
    - keypress: KEYCODE_ENTER
  ben and holly:
    - keypress: KEYCODE_HOME
    - wait: 5
    - app: AMAZON_PKG
      activity: AMAZON_ACT
    - wait: 10
    - keypress: KEYCODE_DPAD_LEFT
    - wait: 1
    - keypress: KEYCODE_ENTER
    - wait: 5
    - text: ben and holly
    - wait: 5
    - keypress: KEYCODE_DPAD_UP
    - wait: 1
    - keypress: KEYCODE_ENTER
    - wait: 2
    - keypress: KEYCODE_DPAD_DOWN
    - wait: 1
    - keypress: KEYCODE_ENTER
buttons:
  enter: KEYCODE_ENTER
  play: KEYCODE_MEDIA_PLAY
  pause: KEYCODE_MEDIA_PAUSE
  stop: KEYCODE_MEDIA_STOP
  up: KEYCODE_DPAD_UP
  down: KEYCODE_DPAD_DOWN
  left: KEYCODE_DPAD_LEFT
  right: KEYCODE_DPAD_RIGHT
  home: KEYCODE_HOME
  back: KEYCODE_BACK
  tv: KEYCODE_TV

apps:
  NETFLIX_PKG: com.netflix.ninja
  AMAZON_PKG: com.amazon.amazonvideo.livingroom
  HULU_PKG: com.hulu.livingroomplus
  YOUTUBE_PKG: com.google.android.youtube.tv
  VUDU_PKG: air.com.vudu.air.DownloaderTablet
  SETTINGS_PKG: com.android.tv.settings
  PSVUE_PKG: com.snei.vue.atv
  PARENTALLOCK_PKG: com.sony.dtv.tvsettingsbroadcast
  SONY_SELECT_PKG: com.sony.dtv.sonyselect

activities:
  NETFLIX_ACT: com.netflix.ninja.MainActivity
  AMAZON_ACT: com.amazon.ignition.IgnitionActivity
  HULU_ACT: com.hulu.livingroomplus.MainActivity
  YOUTUBE_ACT: com.google.android.apps.youtube.tv.activity.ShellActivity
  VUDU_ACT: com.vudu.android.app.activities.NavigationListActivity
  SETTINGS_ACT: com.sony.dtv.settings.MainSettings
  PSVUE_ACT: com.snei.vue.ui.MainActivity
  PARENTALLOCK_ACT: com.sony.dtv.tvsettings.parentalcontrolsetting.activities.ParentalLockActivity
  SONY_SELECT_ACT: com.sony.dtv.sonyselect.activities.LaunchActivity



keycodes:
  KEYCODE_UNKNOWN: 0
  KEYCODE_MENU: 1
  KEYCODE_SOFT_RIGHT: 2
  KEYCODE_HOME: 3
  KEYCODE_BACK: 4
  KEYCODE_CALL: 5
  KEYCODE_ENDCALL: 6
  KEYCODE_0: 7
  KEYCODE_1: 8
  KEYCODE_2: 9
  KEYCODE_3: 10
  KEYCODE_4: 11
  KEYCODE_5: 12
  KEYCODE_6: 13
  KEYCODE_7: 14
  KEYCODE_8: 15
  KEYCODE_9: 16
  KEYCODE_STAR: 17
  KEYCODE_POUND: 18
  KEYCODE_DPAD_UP: 19
  KEYCODE_DPAD_DOWN: 20
  KEYCODE_DPAD_LEFT: 21
  KEYCODE_DPAD_RIGHT: 22
  KEYCODE_DPAD_CENTER: 23
  KEYCODE_VOLUME_UP: 24
  KEYCODE_VOLUME_DOWN: 25
  KEYCODE_POWER: 26
  KEYCODE_CAMERA: 27
  KEYCODE_CLEAR: 28
  KEYCODE_A: 29
  KEYCODE_B: 30
  KEYCODE_C: 31
  KEYCODE_D: 32
  KEYCODE_E: 33
  KEYCODE_F: 34
  KEYCODE_G: 35
  KEYCODE_H: 36
  KEYCODE_I: 37
  KEYCODE_J: 38
  KEYCODE_K: 39
  KEYCODE_L: 40
  KEYCODE_M: 41
  KEYCODE_N: 42
  KEYCODE_O: 43
  KEYCODE_P: 44
  KEYCODE_Q: 45
  KEYCODE_R: 46
  KEYCODE_S: 47
  KEYCODE_T: 48
  KEYCODE_U: 49
  KEYCODE_V: 50
  KEYCODE_W: 51
  KEYCODE_X: 52
  KEYCODE_Y: 53
  KEYCODE_Z: 54
  KEYCODE_COMMA: 55
  KEYCODE_PERIOD: 56
  KEYCODE_ALT_LEFT: 57
  KEYCODE_ALT_RIGHT: 58
  KEYCODE_SHIFT_LEFT: 59
  KEYCODE_SHIFT_RIGHT: 60
  KEYCODE_TAB: 61
  KEYCODE_SPACE: 62
  KEYCODE_SYM: 63
  KEYCODE_EXPLORER: 64
  KEYCODE_ENVELOPE: 65
  KEYCODE_ENTER: 66
  KEYCODE_DEL: 67
  KEYCODE_GRAVE: 68
  KEYCODE_MINUS: 69
  KEYCODE_EQUALS: 70
  KEYCODE_LEFT_BRACKET: 71
  KEYCODE_RIGHT_BRACKET: 72
  KEYCODE_BACKSLASH: 73
  KEYCODE_SEMICOLON: 74
  KEYCODE_APOSTROPHE: 75
  KEYCODE_SLASH: 76
  KEYCODE_AT: 77
  KEYCODE_NUM: 78
  KEYCODE_HEADSETHOOK: 79
  KEYCODE_FOCUS: 80
  KEYCODE_PLUS: 81
  KEYCODE_MENU: 82
  KEYCODE_NOTIFICATION: 83
  KEYCODE_SEARCH: 84
  TAG_LAST_KEYCODE: 85
